class AddSkillsToDb < ActiveRecord::Migration[5.1]
  def up
    add_column :skills, :kind, :integer, null: false, default: 0
    Skill.all.each(&:destroy)
    generic = [
      "Gestão do Tempo",
      "Domínio dos Procedimentos Internos e Externos",
      "Adaptabilidade",
      "Proactividade e Iniciativa",
      "Comprometimento e Orientação para Presultados",
      "Planeamento e Organização",
      "Relacionamento Interpessoal",
      "Serviço ao Cliente",
      "Trabalho em Equipa",
      "Capacidade de Comunicar de forma eficaz e eficiente",
      "Saber Escutar",
      "Ética e Sigilo Profissional",
      "Auto-controle Emocional",
      "Capacidade de Desenvolvimento Pessoal"
    ]
    specific = [
      "Domínio dos Normativos e Leis",
      "Domínio da Fiscalidade",
      "Conduzir Reuniões",
      "Liderança de Equipas",
      "Inovação e criatividade",
      "Tomada de Decisão",
      "Gerir Conflitos",
      "Intervenção Estratégica",
      "Capacidade de transmitir conhecimentos",
      "Transformar informações quantitativas em Insights",
      "Domínio do Storytelling",
      "Conhecimentos de Plataformas de TI e Canais de Comunicação",
      "Análise Financeira",
      "Capacidade Investigativa",
      "Networking",
      "Capacidade de Negociação",
      "Criatividade",
      "Organizar e Gerir Eventos",
      "Definição de Objectivos",
      "Domínio da L. Portuguesa",
      "Domínio de Lin. Estrangeiras",
      "Técnica de Vendas",
      "Orientação para o Cliente",
      "Domínio de Ferramentas Tecnológicas (MSOffice)",
      "Aptidão Numérica",
      "Análise de Crédito",
      "Protocolo e Gestão Eventos",
      "Gestão de Imagem e Comunicação", 
      "Gestão do Produto Bancário",
      "Domínio de Contabilidade Bancária",
      "Domínio de Branqueamento de Capitais",
      "Domínio de Direito Laboral",
      "Domínio de Direito Bancário",
      "Domínio de Direito Fiscal",
      "Domínio de Direito Comercial", 
      "Domínio de Redes e Sistemas Informáticos",
      "Domínio de Segurança de Dados Electrónica",
      "Gestão de Projectos",
      "Gestão de Frotas",
      "Higiene e Segurança no Trabalho",
      "Qualidade, Aprovisionamento e Gestão de Stocks",
      "Gestão Operacional de Imobilizado",
      "Domínio de MSProject",
      "Gestão Arquivo",
      "Conhecimento da Estrutura da Organização",
      "Técnicas e Operações Bancárias",
      "Análise de Investimentos",
      "Técnicas de Gestão de Risco",
      "Técnicas de Recuperação Crédito",
      "Elaborar Pareceres e Relatórios de Actividade",
      "Atendimento ao Público",
      "Mercados Financeiros",
      "Conhecimento em Estudos de Viabilidade",
      "Estratégia de Continuidade de Negócio",
      "Análise de Impacto no Negócio",
      "Sistemas e meios de Pagamento",
      "Gestão de Reclamações",
      "Técnicas e controlo de fraudes",
      "Gestão e Acompanhamento de Sinistros",
      "Domínio do Produto Seguros",
      "Técnicas de Atendimento ao Público",
      "Destreza e manuseamento de viaturas",
      "Conhecimentos básicos de mecanica", 
      "Sentido de Responsabilidade",
      "Destreza Ferramentas Tecnológicas",
      "Assiduídade e Pontualidade",
      "Técnicas de limpeza de espaços profissionais",
      "Conhecimento de estrutura electrica, Hardware",
      "Técnicas de Arquivo e secretariado",
      "Contratualização",
      "Técnicas de Processamento Crédito",
      "Relações Internacionais",
      "Corporate Finance",
      "Gestão de Relações Institucionais"
    ]
    Skill.create(specific.map{|s| {name: s}} + generic.map{|g| {name: g, kind: 1}})
  end

  def down
    remove_column :skills, :kind, :integer, null: false, default: 0 if column_exists? :skills, :kind
    Skill.all.each(&:destroy)
  end
end
