class AddReaddFunctions < ActiveRecord::Migration[5.1]
  def up
    functions = [
      ["DIRECTOR","DNI"],
      ["SUBDIRECTOR",	"DNI"],
      ["COORDENADOR",	"DNI"],
      ["CHEFE",	"DNI"],
      ["TÉCNICO",	"DNI"],
      ["DIRECTOR","DGE"],
      ["SUBDIRECTOR","DGE"],
      ["RESPONSÁVEL CE","DGE"],
      ["GESTOR CONTA","DGE"],
      ["DIRECTOR","DPME"],
      ["SUBDIRECTOR","DPME"],
      ["GESTOR CONTA","DPME"],
      ["DIRECTOR","DPT"],
      ["SUBDIRECTOR","DPT"],
      ["COORDENADOR","DPT"],
      ["GERENTE BALCÃO","DPT"],
      ["SUBGERENTE BALCÃO","DPT"],
      ["GERENTE POSTO","DPT"],
      ["TESOUREIRO","DPT"],
      ["ASSISTENTE TESOUREIR","DPT"],
      ["FRONTOFFICE","DPT"],
      ["RECONTADOR","DPT"],
      ["DIRECTOR","PRIVATE"],
      ["SUBDIRECTOR","PRIVATE"],
      ["GESTOR CONTA PRIVATE","PRIVATE"],
      ["DIRECTOR","DMC"],
      ["SUBDIRECTOR","DMC"],
      ["CHEFE","DMC"],
      ["TÉCNICO","DMC"],
      ["CHEFE","DMC"],
      ["TÉCNICO","DMC"],
      ["CHEFE","DMC"],
      ["TÉCNICO","DMC"],
      ["GESTOR MICROCRÉDITO","DMC"],
      ["AGENTE MICROCRÉDITO","DMC"],
      ["DIRECTOR","DBI"],
      ["SUBDIRECTOR",	"DBI"],
      ["CHEFE",	"DBI"],
      ["TÉCNICO",	"DBI"],
      ["DIRECTOR","DBA"],
      ["SUBDIRECTOR","DBA"],
      ["CHEFE","DBA"],
      ["TÉCNICO","DBA"],
      ["DIRECTOR","DPE"],
      ["SUBDIRECTOR",	"DPE"],
      ["CHEFE",	"DPE"],
      ["TÉCNICO",	"DPE"],
      ["DIRECTOR","DAI"],
      ["SUBDIRECTOR","DAI"],
      ["CHEFE","DAI"],
      ["TÉCNICO","DAI"],
      ["CHEFE","DAI"],
      ["TÉCNICO","DAI"],
      ["CHEFE","DAI"],
      ["TÉCNICO","DAI"],
      ["DIRECTOR","DCP"],
      ["SUBDIRECTOR","DCP"],
      ["CHEFE","DCP"],
      ["TÉCNICO","DCP"],
      ["CHEFE","DCP"],
      ["TÉCNICO","DCP"],
      ["DIRECTOR","DGR"],
      ["SUBDIRECTOR","DGR"],
      ["CHEFE","DGR"],
      ["TECNICO","DGR"],
      ["CHEFE","DGR"],
      ["TECNICO","DGR"],
      ["DIRECTOR","RH"],
      ["SUBDIRECTOR","RH"],
      ["CHEFE","RH"],
      ["TECNICO","RH"],
      ["CHEFE","RH"],
      ["TECNICO","RH"],
      ["CHEFE","RH"],
      ["TECNICO","RH"],
      ["RECEPCIONISTAS","RH"],
      ["DIRECTOR","DDI"],
      ["SUBDIRECTOR","DDI"],
      ["CHEFE","DDI"],
      ["TÉCNICO","DDI"],
      ["CHEFE","DDI"],
      ["TÉCNICO","DDI"],
      ["DIRECTOR","DRI"],
      ["DIRECTOR","DOP"],
      ["SUBDIRECTOR","DOP"],
      ["CHEFE","DOP"],
      ["TÉCNICO","DOP"],
      ["CHEFE","DOP"],
      ["TÉCNICO","DOP"],
      ["CHEFE","DOP"],
      ["TÉCNICO","DOP"],
      ["CHEFE","DOP"],
      ["TÉCNICO","DOP"],
      ["DIRECTOR","DAPC"],
      ["SUBDIRECTOR","DAPC"],
      ["CHEFE","DAPC"],
      ["TÉCNICO","DAPC"],
      ["CHEFE","DAPC"],
      ["TÉCNICO","DAPC"],
      ["CHEFE","DAPC"],
      ["TÉCNICO","DAPC"],
      ["CHEFE","DAPC"],
      ["TÉCNICO","DAPC"],
      ["DIRECTOR","DGR"],
      ["SUBDIRECTOR","DGR"],
      ["CHEFE","DGR"],
      ["TECNICO","DGR"],
      ["DIRECTOR","DFI"],
      ["SUBDIRECTOR","DFI"],
      ["CHEFE","DFI"],
      ["TECNICO","DFI"],
      ["CHEFE","DFI"],
      ["TECNICO","DFI"],
      ["CHEFE","DFI"],
      ["TECNICO","DFI"],
      ["DIRECTOR","DTI"],
      ["SUBDIRECTOR","DTI"],
      ["CHEFE","DTI"],
      ["TECNICO","DTI"],
      ["DIRECTOR","DBE"],
      ["SUBDIRECTOR","DBE"],
      ["CHEFE","DBE"],
      ["TÉCNICO","DBE"],
      ["CHEFE","DBE"],
      ["TÉCNICO","DBE"],
      ["CHEFE","DBE"],
      ["TÉCNICO","DBE"],
      ["SUPERVISOR","DBE"],
      ["TÉCNICO","DBE"],
      ["DIRECTOR","DMK"],
      ["SUBDIRECTOR","DMK"],
      ["CHEFE","DMK"],
      ["TÉCNICO","DMK"],
      ["CHEFE","DMK"],
      ["TÉCNICO","DMK"],
      ["CHEFE","DMK"],
      ["TÉCNICO","DMK"],
      ["DIRECTOR","DCO"],
      ["SUBDIRECTOR","DCO"],
      ["CHEFE","DCO"],
      ["TECNICO","DCO"],
      ["CHEFE","DCO"],
      ["TECNICO","DCO"],
      ["CHEFE","DCO"],
      ["TECNICO","DCO"],
      ["DIRECTOR","JURIDICA"],
      ["SUBDIRECTOR","JURIDICA"],
      ["CHEFE","JURIDICA"],
      ["TECNICO","JURIDICA"],
      ["CHEFE","JURIDICA"],
      ["TECNICO","JURIDICA"],
      ["DIRECTOR","DPS"],
      ["SUBDIRECTOR","DPS"],
      ["CHEFE","DPS"],
      ["TECNICO","DPS"],
      ["CHEFE","DPS"],
      ["TECNICO","DPS"],
      ["CHEFE","DPS"],
      ["TECNICO","DPS"],
      ["CHEFE","DPS"],
      ["TECNICO","DPS"],
      ["CHEFE","DPS"],
      ["TECNICO","DPS"],
      ["CHEFE","DPS"],
      ["TECNICO","DPS"],
      ["CHEFE","DPS"],
      ["TECNICO","DPS"]
    ]
    dirs = Directorate.all.index_by(&:abbreviation)
    p Function.create(functions.map{|f| {name: f.first.to_s.next_titleize, directorate_id: dirs[f.last]&.id}}).map{|f| [f, f.errors.messages]}
  end

  def down

  end
end
