class InserirInformacoesDeProvinciasEMunicipios < ActiveRecord::Migration[5.1]
  def change
     bie = Province.create(name: "Bié")
     bengo = Province.create(name: "Bengo")
     benguela = Province.create(name: "Benguela")
     cabinda = Province.create(name: "Cabinda")
     cunene = Province.create(name: "cunene.id)")
     huila = Province.create(name: "Huila)")
     huambo = Province.create(name: "Huambo)")
     kwanza_sul =Province.create(name: "Kwanza Sul")
     kwanza_norte = Province.create(name: "Kwanza Norte")
     kuando_kubango =Province.create(name: "Kuando Kubango")
     luanda = Province.create(name: "Luanda)")
     lunda_norte = Province.create(name: "Lunda Norte")
     lunda_sul = Province.create(name: "Lunda sul")
     malanje = Province.create(name: "Malanje")
     moxico = Province.create(name: "Moxico")
     namibe = Province.create(name: "Namibe")
     uige = Province.create(name: "Uíge")
     zaire = Province.create(name: "Zaire")

     Municipality.create(name: "Ambriz", province_id: 	bengo.id)
     Municipality.create(name: "Bula Atumba", province_id: 	bengo.id)
     Municipality.create(name: "Dande", province_id: 	bengo.id)
     Municipality.create(name: "Dembos", province_id: 	bengo.id)
     Municipality.create(name: "Nambuangongo", province_id: 	bengo.id)
     Municipality.create(name: "Pango Aluquém", province_id: 	bengo.id)
     Municipality.create(name: "Balombo", province_id: 	benguela.id)
     Municipality.create(name: "Baía Farta", province_id: 	benguela.id)
     Municipality.create(name: "Benguela", province_id: 	benguela.id)
     Municipality.create(name: "Bocoio", province_id: 	benguela.id)
     Municipality.create(name: "Caimbambo", province_id: 	benguela.id)
     Municipality.create(name: "Chongorói", province_id: 	benguela.id)
     Municipality.create(name: "Cubal", province_id: 	benguela.id)
     Municipality.create(name: "Ganda", province_id: 	benguela.id)
     Municipality.create(name: "Lobito", province_id: 	benguela.id)
     Municipality.create(name: "Andulo", province_id: 	bie.id)
     Municipality.create(name: "Camacupa", province_id: 	bie.id)
     Municipality.create(name: "Catabola", province_id: 	bie.id)
     Municipality.create(name: "Chinguar", province_id: 	bie.id)
     Municipality.create(name: "Chitembo", province_id: 	bie.id)
     Municipality.create(name: "Cuemba", province_id: 	bie.id)
     Municipality.create(name: "Cunhinga", province_id: 	bie.id)
     Municipality.create(name: "Kuito", province_id: 	bie.id)
     Municipality.create(name: "Nharea", province_id: 	bie.id)
     Municipality.create(name: "Belize", province_id: 	cabinda.id)
     Municipality.create(name: "Buco-Zau", province_id: 	cabinda.id)
     Municipality.create(name: "Cabinda", province_id: 	cabinda.id)
     Municipality.create(name: "Cacongo", province_id: 	cabinda.id)
     Municipality.create(name: "Calai", province_id: 	kuando_kubango.id)
     Municipality.create(name: "Cuangar", province_id: 	kuando_kubango.id)
     Municipality.create(name: "Cuchi", province_id: 	kuando_kubango.id)
     Municipality.create(name: "Cuito Cuanavale", province_id: 	kuando_kubango.id)
     Municipality.create(name: "Dirico", province_id: 	kuando_kubango.id)
     Municipality.create(name: "Longa", province_id: 	kuando_kubango.id)
     Municipality.create(name: "Mavinga", province_id: 	kuando_kubango.id)
     Municipality.create(name: "Menongue", province_id: 	kuando_kubango.id)
     Municipality.create(name: "Rivungo", province_id: 	kuando_kubango.id)
     Municipality.create(name: "Ambaca", province_id: 	kwanza_norte.id)
     Municipality.create(name: "Banga", province_id: 	kwanza_norte.id)
     Municipality.create(name: "Bolongongo", province_id: 	kwanza_norte.id)
     Municipality.create(name: "Cambambe", province_id: 	kwanza_norte.id)
     Municipality.create(name: "Cazengo", province_id: 	kwanza_norte.id)
     Municipality.create(name: "Golungo Alto", province_id: 	kwanza_norte.id)
     Municipality.create(name: "Gonguembo", province_id: 	kwanza_norte.id)
     Municipality.create(name: "Lucala", province_id: 	kwanza_norte.id)
     Municipality.create(name: "Quiculungo", province_id: 	kwanza_norte.id)
     Municipality.create(name: "Samba Caju", province_id: 	kwanza_norte.id)
     Municipality.create(name: "Amboim", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Cassongue", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Cela", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Conda", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Ebo", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Libolo", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Mussende", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Quibala", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Quilenda", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Seles", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Sumbe", province_id: 	kwanza_sul.id)
     Municipality.create(name: "Cahama", province_id: 	cunene.id)
     Municipality.create(name: "Cuanhama", province_id: 	cunene.id)
     Municipality.create(name: "Curoca", province_id: 	cunene.id)
     Municipality.create(name: "Cuvelai", province_id: 	cunene.id)
     Municipality.create(name: "Namacunde", province_id: 	cunene.id)
     Municipality.create(name: "Ombadja", province_id: 	cunene.id)
     Municipality.create(name: "Bailundo", province_id: 	huambo.id)
     Municipality.create(name: "Catchiungo", province_id: 	huambo.id)
     Municipality.create(name: "Caála", province_id: 	huambo.id)
     Municipality.create(name: "Ekunha", province_id: 	huambo.id)
     Municipality.create(name: "Huambo)", province_id: 	huambo.id)
     Municipality.create(name: "Londuimbale", province_id: 	huambo.id)
     Municipality.create(name: "Longonjo", province_id: 	huambo.id)
     Municipality.create(name: "Mungo", province_id: 	huambo.id)
     Municipality.create(name: "Tchicala-Tcholoanga", province_id: 	huambo.id)
     Municipality.create(name: "Tchindjenje", province_id: 	huambo.id)
     Municipality.create(name: "Ucuma", province_id: 	huambo.id)
     Municipality.create(name: "Caconda", province_id: 	huila.id)
     Municipality.create(name: "Caluquembe", province_id: 	huila.id)
     Municipality.create(name: "Chiange", province_id: 	huila.id)
     Municipality.create(name: "Chibia", province_id: 	huila.id)
     Municipality.create(name: "Chicomba", province_id: 	huila.id)
     Municipality.create(name: "Chipindo", province_id: 	huila.id)
     Municipality.create(name: "Cuvango", province_id: 	huila.id)
     Municipality.create(name: "Humpata", province_id: 	huila.id)
     Municipality.create(name: "Jamba", province_id: 	huila.id)
     Municipality.create(name: "Lubango", province_id: 	huila.id)
     Municipality.create(name: "Matala", province_id: 	huila.id)
     Municipality.create(name: "Quilengues", province_id: 	huila.id)
     Municipality.create(name: "Quipungo", province_id: 	huila.id)
     Municipality.create(name: "Belas", province_id: 	luanda.id)
     Municipality.create(name: "Talatona", province_id: 	luanda.id)
     Municipality.create(name: "Cacuaco", province_id: 	luanda.id)
     Municipality.create(name: "Cazenga", province_id: 	luanda.id)
     Municipality.create(name: "Ícolo e Bengo", province_id: 	luanda.id)
     Municipality.create(name: "Luanda)", province_id: 	luanda.id)
     Municipality.create(name: "Quissama", province_id: 	luanda.id)
     Municipality.create(name: "Viana", province_id: 	luanda.id)
     Municipality.create(name: "Capenda-Camulemba", province_id: 	lunda_norte.id)
     Municipality.create(name: "Caungula", province_id: 	lunda_norte.id)
     Municipality.create(name: "Chitato", province_id: 	lunda_norte.id)
     Municipality.create(name: "Cuango", province_id: 	lunda_norte.id)
     Municipality.create(name: "Cuílo", province_id: 	lunda_norte.id)
     Municipality.create(name: "Lubalo", province_id: 	lunda_norte.id)
     Municipality.create(name: "Xá-Muteba", province_id: 	lunda_norte.id)
     Municipality.create(name: "Cambulo", province_id: 	lunda_norte.id)
     Municipality.create(name: "Cacolo", province_id: 	lunda_sul.id)
     Municipality.create(name: "Dala", province_id: 	lunda_sul.id)
     Municipality.create(name: "Muconda", province_id: 	lunda_sul.id)
     Municipality.create(name: "Saurimo", province_id: 	lunda_sul.id)
     Municipality.create(name: "Cacuso", province_id: 	malanje.id)
     Municipality.create(name: "Calandula", province_id: 	malanje.id)
     Municipality.create(name: "Cambundi-Catembo", province_id: 	malanje.id)
     Municipality.create(name: "Cangandala", province_id: 	malanje.id)
     Municipality.create(name: "Caombo", province_id: 	malanje.id)
     Municipality.create(name: "Cuaba Nzogo", province_id: 	malanje.id)
     Municipality.create(name: "Cunda-Dia-Baze", province_id: 	malanje.id)
     Municipality.create(name: "Luquembo", province_id: 	malanje.id)
     Municipality.create(name: "Malanje", province_id: 	malanje.id)
     Municipality.create(name: "Marimba", province_id: 	malanje.id)
     Municipality.create(name: "Massango", province_id: 	malanje.id)
     Municipality.create(name: "Mucari", province_id: 	malanje.id)
     Municipality.create(name: "Quela", province_id: 	malanje.id)
     Municipality.create(name: "Quirima", province_id: 	malanje.id)
     Municipality.create(name: "Alto Zambeze", province_id: 	moxico.id)
     Municipality.create(name: "Bundas", province_id: 	moxico.id)
     Municipality.create(name: "Camanongue", province_id: 	moxico.id)
     Municipality.create(name: "Luacano", province_id: 	moxico.id)
     Municipality.create(name: "Luau", province_id: 	moxico.id)
     Municipality.create(name: "Luchazes", province_id: 	moxico.id)
     Municipality.create(name: "Léua", province_id: 	moxico.id)
     Municipality.create(name: "Moxico", province_id: 	moxico.id)
     Municipality.create(name: "Bibala", province_id: 	namibe.id)
     Municipality.create(name: "Camucuio", province_id: 	namibe.id)
     Municipality.create(name: "Moçâmedes", province_id: 	namibe.id)
     Municipality.create(name: "Tômbua", province_id: 	namibe.id)
     Municipality.create(name: "Virei", province_id: 	namibe.id)
     Municipality.create(name: "Alto Cauale", province_id: 	uige.id)
     Municipality.create(name: "Ambuíla", province_id: 	uige.id)
     Municipality.create(name: "Bembe", province_id: 	uige.id)
     Municipality.create(name: "Buengas", province_id: 	uige.id)
     Municipality.create(name: "Damba", province_id: 	uige.id)
     Municipality.create(name: "Macocola", province_id: 	uige.id)
     Municipality.create(name: "Mucaba", province_id: 	uige.id)
     Municipality.create(name: "Negage", province_id: 	uige.id)
     Municipality.create(name: "Puri", province_id: 	uige.id)
     Municipality.create(name: "Quimbele", province_id: 	uige.id)
     Municipality.create(name: "Quitexe", province_id: 	uige.id)
     Municipality.create(name: "Sanza Pombo", province_id: 	uige.id)
     Municipality.create(name: "Songo", province_id: 	uige.id)
     Municipality.create(name: "Uíge", province_id: 	uige.id)
     Municipality.create(name: "Zombo", province_id: 	uige.id)
     Municipality.create(name: "Cuimba", province_id: 	zaire.id)
     Municipality.create(name: "M'Banza Kongo", province_id: 	zaire.id)
     Municipality.create(name: "Noqui", province_id: 	zaire.id)
     Municipality.create(name: "N'Zeto", province_id: 	zaire.id)
     Municipality.create(name: "Soyo", province_id: 	zaire.id)
  end
end
